### ISSUE TITLE
Bug encountered during Tag creation

### ISSUE THREAD

**Issue by kehindeakala** [PaloAltoNetworks/terraform-provider-panos#327]
## Describe the bug
Error: The terraform-provider-panos_v1.10.0 plugin crashed!

## Expected behavior

Tag Resource should successfully be created

## Current behaviour

Not successfully created

## Possible solution
None
## Steps to reproduce

1.  terraform apply --target "module.objects.panos_administrative_tag.untrust"

## Screenshots

Kehinde.Akala@DE-MUC1-MAC0089 tf-panorama % terraform apply --target "module.objects.panos_administrative_tag.untrust"

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # module.objects.panos_administrative_tag.untrust will be created
  + resource "panos_administrative_tag" "untrust" {
      + color   = "color1"
      + comment = "untrust"
      + id      = (known after apply)
      + name    = "untrust"
      + vsys    = "vsys1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the
│ changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from
│ errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.objects.panos_administrative_tag.untrust: Creating...
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been
│ ignored and the output values may not be fully updated. Run the following command to verify that no other changes are
│ pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as
│ recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.objects.panos_administrative_tag.untrust,
│   on modules/objects/tags.tf line 1, in resource "panos_administrative_tag" "untrust":
│    1: resource "panos_administrative_tag" "untrust" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-panos_v1.10.0 plugin:

panic: interface conversion: interface {} is *pango.Panorama, not *pango.Firewall

goroutine 69 [running]:
github.com/terraform-providers/terraform-provider-panos/panos.createAdministrativeTag(0xc000165570, 0x212e7a0, 0xc00000a1e0, 0x2, 0x2ada660)
        github.com/terraform-providers/terraform-provider-panos/panos/resource_administrative_tag.go:71 +0x319
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0006e6000, 0xc0008934a0, 0xc000a36560, 0x212e7a0, 0xc00000a1e0, 0x1f9c001, 0xc000226ac8, 0xc0008f6f00)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000122a80, 0xc000b03a38, 0xc0008934a0, 0xc000a36560, 0xc0006d6508, 0xc000b50b60, 0x1f9dfc0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e318, 0x23711d0, 0xc0008f6540, 0xc000164f50, 0xc00000e318, 0xc0008f6540, 0xc000acfba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x20e9340, 0xc00000e318, 0x23711d0, 0xc0008f6540, 0xc0008c3080, 0x0, 0x23711d0, 0xc0008f6540, 0xc0005de000, 0xb0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bafc0, 0x237a8f8, 0xc00048cc00, 0xc000826200, 0xc00023a870, 0x2a99c40, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001bafc0, 0x237a8f8, 0xc00048cc00, 0xc000826200, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002901d0, 0xc0001bafc0, 0x237a8f8, 0xc00048cc00, 0xc000826200)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-panos_v1.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

## Context

 Yes

## Your Environment

 Dev environment

- Version used: 
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): 
- Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/paloaltonetworks/panos v1.10.0
- Operating System and version (desktop or mobile): Mac BigSur 11.16.3
- Link to your project:

**Comment by kbreit** [comment]
This looks very similar to my https://github.com/PaloAltoNetworks/terraform-provider-panos/issues/326

**Comment by mrhorrible78** [comment]
Just wanted to add that I'm seeing this same issue when creating tags as well, even if the tag is the only object in my Terraform plan so it doesn't seem like it's quite the same as bug #326 above if I was reading it right which seemed to indicate if you mixed both panos and panorama resources in the same state file you might run into problems.  I ran this against a Panorama installation.

#### Issue description
Error: The terraform-provider-panos_v1.10.0 plugin crashed!

#### Steps to reproduce the issue
resource "panos_administrative_tag" "active_directory_tag" {
    name = "tf_active_directory"
    comment = "AD Systems"
}


#### What's the expected result?
Tag created


#### What's the actual result?
Error


#### Additional details / screenshot
terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # panos_administrative_tag.active_directory_tag will be created
  + resource "panos_administrative_tag" "active_directory_tag" {
      + comment = "AD Systems"
      + id      = (known after apply)
      + name    = "tf_active_directory"
      + vsys    = "vsys1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

panos_administrative_tag.active_directory_tag: Creating...
╷
│ Error: Plugin did not respond
│
│   with panos_administrative_tag.active_directory_tag,
│   on main.tf line 15, in resource "panos_administrative_tag" "active_directory_tag":
│   15: resource "panos_administrative_tag" "active_directory_tag" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-panos_v1.10.0 plugin:

panic: interface conversion: interface {} is *pango.Panorama, not *pango.Firewall

goroutine 84 [running]:
github.com/terraform-providers/terraform-provider-panos/panos.createAdministrativeTag(0x14000cb0850, 0x1034c5860, 0x1400058e000, 0x2, 0x103c5e1c0)
	github.com/terraform-providers/terraform-provider-panos/panos/resource_administrative_tag.go:71 +0x230
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x1400056f040, 0x140002c8e10, 0x14000077240, 0x1034c5860, 0x1400058e000, 0x103333201, 0x14000658df8, 0x140003fe360)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x294
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x14000294380, 0x14000bdba20, 0x140002c8e10, 0x14000077240, 0x14000821168, 0x140006e2430, 0x1033351e0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x88
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x14000618348, 0x10350d2b0, 0x14000365980, 0x14000cb0150, 0x14000618348, 0x102823330, 0x103420300)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x6cc
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x103480320, 0x14000618348, 0x10350d2b0, 0x14000365980, 0x14000079e00, 0x0, 0x10350d2b0, 0x14000365980, 0x140004421a0, 0xc2)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x140003596c0, 0x103516df8, 0x140005c2480, 0x14000252700, 0x140002b6510, 0x103c1d980, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x140003596c0, 0x103516df8, 0x140005c2480, 0x14000252700, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400009e1b0, 0x140003596c0, 0x103516df8, 0x140005c2480, 0x14000252700)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

Error: The terraform-provider-panos_v1.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by mrhorrible78** [comment]
I was running into this same issue, too.  But it turned out I was running the panos_administrative_tag resource against my Panorama instance rather than using panos_panorama_administrative_tag.  When I switched, I stopped getting this error.  It'd be great if this exception was caught and we get an error message along the lines of "Hey, looks like you're using the wrong resource type here - maybe you meant to use the <Firewall or Panorama> resource type instead?" rather than this error that looks like an uncaught exception.

**Comment by shinmog** [comment]
The `panos` provider has started converging resources, so that `panos_administrative_tag` and `panos_panorama_administrative_tag` are the same code, but this work is not yet complete.  As a stop-gap, I can at least do the nice error message in these two resources instead of the crash.
