### ISSUE TITLE
Audit_comment in panos_security_rule_group not working

### ISSUE THREAD

**Issue by Marek-Madi** [PaloAltoNetworks/terraform-provider-panos#339]
## Describe the bug

Audit_comment in panos_security_rule_group not working. When you set it up, it doesn't update anything on the Panorama

## Expected behavior

Audit_comment should update the rule with audit_comment

## Current behavior

audit_comment in "rule" section not working

## Possible solution

N/A

## Steps to reproduce

Use resource panos_security_rule_group with rule with audit_comment specified

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by Marek-Madi** [comment]
I am ussing map of objects for the security rules. When I add new security rule to the map, I am expecting that to show the audit comment. Or even when I am updating the rule within the map the `audit_comment` is not present. I am not sure then if I understand when is the param considered then ? Do I have to create new resource for every rule in order for the `audit_comment` to be visible ?

**Comment by shinmog** [comment]
Hrm, I think the best thing to do here is to create a special documentation section in the docs discussing how audit comments work in PAN-OS.

But to answer your question, you do not need to create a whole resource for audit comments to be considered.  Audit comments are applicable per rule inside a resource, and applied when that rule has to be either 1) created or 2) updated.

Let's take an example.

Let's say you have a single `panos_security_rule_group` resource named "foo" that has 3 security rules in it:  s1, s2, and s3.  Then you decide that you need to add s4 to this, and also update something about s2's configuration.  When you do `terraform apply` with this new configuration, the provider sees that s2 has changed spec, so s2 is updated, then if s2 has an audit comment defined, s2's `audit_comment` is applied.  Then it sees a new rule is present, s4, so that is created and, assuming s4 has an audit comment defined, s4's `audit_comment` is applied.  Since there are no changes to s1 or s3, their `audit_comment` specs are ignored.

The audit comment as stored in the local state file will always be an empty string.  This is because of a number of reasons, but the easiest to communicate is performance.

The PAN-OS API does not allow for the retrieval of every single rule's audit comment in one API call the same way it allows for retrieving their configuration.  If you have 1,000 security rules, that's 1,000 extra API calls to get the audit comment configuration.  Let's say the round trip is half a second for each API call, that's 500 seconds, or just over 8 minutes just to complete the read operation.

So, this is why the logic for `audit_comment` is basically "apply the `audit_comment` when the rule spec changes," and why diffs are disabled for `audit_comment` params.
